---
use_cache: False # Use cache
followup_prob: 0.9 # Probabilty coverage of follow-up
z_min_b: 0.01 # Minimum redshift for background
z_max_b: 1.0 # Maximum redshift for background
frac_det: 1.0 # Fraction of flares detected
dt_followup: 200.0 # Length of follow-up campaign in days
gwmapdir: "/hildafs/projects/phy220048p/share/skymaps"
gw_csv: "/hildafs/projects/phy220048p/tcabrera/bbhagn/bbhagn/data/graham23_tables/gw.csv"
flare_csv: "/hildafs/projects/phy220048p/tcabrera/bbhagn/bbhagn/data/graham23_tables/flare.csv"

# Mass cuts
bbhmass_type: "final_mass_source" # Type of mass to apply cuts to
bbhmass_min: 40.0 # Lower limit for BBH mass in solar masses
bbhmass_max: 200.0 # Upper limit for BBH mass in solar masses

# AGN distribution
agn_distribution:
  astrophysical:
    model: "Milliquas"
    args: []
    kwargs: {}
    density_args: []
    density_kwargs: {}
  observed:
    model: "QLFHopkins"
    args: []
    kwargs: {}
    density_args: []
    density_kwargs:
      brightness_limits: [20.5, "-inf"]
      brightness_units: "ABmag"
      band: "g"

# Flare rate
flare_rate:
  model: "ConstantRate"
  args:
    - 1.06e-8 # Rate from Graham+23, Table 5, in flares/AGN/day (note p_flare is originally normalized to 200 days)
  kwargs: {}
  distribution:
    type: "normal"
    kwargs:
      scale: 3.73e-8

# MCMC parameters
lambda0: 0.2 # Initial lambda for MCMC
H00: 70.0 # Initial H0 for MCMC
Om0: 0.3 # Initial Omega_m for MCMC
nwalkers: 32 # Number of walkers
nsteps: 5000 # Number of steps
nproc: 32 # Number of processes
